sudo: false

language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - mongodb
  - redis-server

env:
  global:
    - TESTS_ZEND_CACHE_APC_ENABLED=true
    - TESTS_ZEND_CACHE_MEMCACHED_ENABLED=true
    - TESTS_ZEND_CACHE_MEMCACHED_HOST='127.0.0.1'
    - TESTS_ZEND_CACHE_MEMCACHED_PORT=11211
    - TESTS_ZEND_CACHE_MEMCACHE_ENABLED=true
    - TESTS_ZEND_CACHE_MEMCACHE_HOST=$TESTS_ZEND_CACHE_MEMCACHED_HOST
    - TESTS_ZEND_CACHE_MEMCACHE_PORT=$TESTS_ZEND_CACHE_MEMCACHED_PORT
    - TESTS_ZEND_CACHE_MONGODB_ENABLED=true
    - TESTS_ZEND_CACHE_REDIS_ENABLED=true
    - TESTS_ZEND_CACHE_REDIS_HOST='127.0.0.1'
    - TESTS_ZEND_CACHE_REDIS_PORT=6379
    - TESTS_ZEND_CACHE_REDIS_PASSWORD=''
    - TESTS_ZEND_CACHE_REDIS_DATABASE=0
    - TESTS_ZEND_CACHE_XCACHE_ENABLED=true
    - TESTS_ZEND_CACHE_XCACHE_ADMIN_AUTH=true
    - TESTS_ZEND_CACHE_XCACHE_ADMIN_USER=travis
    - TESTS_ZEND_CACHE_XCACHE_ADMIN_PASS=test

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
        - PECL_INSTALL_APCU='apcu-4.0.8'
        - INSTALL_XCACHE=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - PECL_INSTALL_APCU='apcu-4.0.8'
        - INSTALL_XCACHE=true
    - php: 7
      env:
        - PECL_INSTALL_APCU='apcu'
        - PECL_INSTALL_APCU_BC='apcu_bc-beta'
    - php: hhvm
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - pwd=$(pwd) ;
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs
  - if [[ $INSTALL_XCACHE == 'true' ]]; then
        git clone https://github.com/lighttpd/xcache.git && cd xcache
        && git checkout $(git rev-list --tags --max-count=1)
        && phpize && ./configure --enable-xcache && make install
        && phpenv config-add $pwd/.ci/xcache.ini
        || return 0 ;
        cd $pwd ;
    fi
  - if [[ $PECL_INSTALL_APCU != '' ]]; then echo "yes\nno\n" | pecl install $PECL_INSTALL_APCU || return 0 ; fi
  # see https://pear.php.net/bugs/bug.php?id=21007
  # pecl install adds the "extension=*.so" directive on top of php.ini which results in wrong extension order
  # -> Attach another ini file loading the extension kind of solves the issue.
  #    The first extension loading still results in a warning but it doesn't break the test
  - if [[ $PECL_INSTALL_APCU_BC != '' ]]; then pecl install $PECL_INSTALL_APCU_BC && phpenv config-add .ci/apcu_bc.ini || return 0 ; fi

before_script:
  - phpenv config-add .ci/php.ini || return 0

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
