docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Storage:
        - Adapters: storage/adapter.md
        - Capabilities: storage/capabilities.md
        - Plugins: storage/plugin.md
    - "Cache Patterns":
        - Introduction: pattern/intro.md
        - CallbackCache: pattern/callback-cache.md
        - ClassCache: pattern/class-cache.md
        - ObjectCache: pattern/object-cache.md
        - OutputCache: pattern/output-cache.md
        - CaptureCache: pattern/capture-cache.md
site_name: laminas-cache
site_description: Laminas\Cache
repo_url: 'https://github.com/laminas/laminas-cache'
